### ISSUE TITLE
No dataset associated found.

### ISSUE THREAD

**Issue by i-m-karanagarwal** [RutujaaP/Evaluation-of-Boosting-Algorithms-for-P300-Detection-in-EEG-Signals#1]
There was no dataset associated with the code found as to test the code.
![image](https://user-images.githubusercontent.com/77572300/153767606-7ae77327-3ed4-4dc0-8748-9d50c50a3b00.png)

**Comment by Watchingyou7** [comment]
Boost signal samsung device

**Comment by RutujaaP** [comment]
Please refer to this Dataset- https://www.kaggle.com/c/inria-bci-challenge
